In [1]:
from model import Inference, GPTConfig, GPTModel, Tokenizor, InternalWeights


/Users/dimbul/Desktop/personal/deep-learning/llm-training/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
#GPT2 Model im Implementation 
gpt_conf = GPTConfig()
gpt_model, hf_weights = GPTModel(gpt_conf).load_pretrained_weights()
gpt_state = gpt_model.state_dict()

copying the data


In [13]:
input = "Hello, I'm a language model,"
#input = ["Hello, I'm a language model,"]
t = Tokenizor()
inf = Inference(model=gpt_model, tokenizor=t)
tokens = t.tokenize(input=input, B=1)


In [14]:
inf.sample(idx=tokens, seq_len=30)

Batch Size 1
Current Token lenght 8
> Hello, I'm a language model, not a designer. That's all."

Advertisement

"You're in a lot of trouble,"


In [15]:
iw = InternalWeights(model=gpt_model, tokenizor=t)


In [16]:
atten_weights = iw.get_atten(idx = tokens, seq_len=5)

Batch Size 1
Current Token lenght 8


In [17]:
len(atten_weights[0])

1

In [18]:
tokens

tensor([[15496,    11,   314,  1101,   257,  3303,  2746,    11]])

In [21]:
layer1 = atten_weights[0]

In [23]:
layer1.size()

torch.Size([1, 12, 8, 8])

In [36]:
h = 0
layer1[0][1]



tensor([[1.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00],
        [6.7076e-03, 9.9329e-01, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00],
        [7.5624e-03, 8.4049e-03, 9.8403e-01, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00],
        [1.4310e-03, 2.6437e-03, 4.4032e-03, 9.9152e-01, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00],
        [1.7698e-03, 4.8090e-03, 4.1432e-03, 3.2679e-04, 9.8895e-01, 0.0000e+00,
         0.0000e+00, 0.0000e+00],
        [1.3257e-02, 1.4160e-03, 1.2549e-02, 1.0162e-02, 1.6027e-03, 9.6101e-01,
         0.0000e+00, 0.0000e+00],
        [4.5448e-04, 4.6352e-04, 1.0316e-03, 8.2328e-04, 5.8749e-05, 3.9128e-04,
         9.9678e-01, 0.0000e+00],
        [1.2156e-03, 4.8873e-01, 2.0043e-03, 3.2256e-04, 2.6163e-04, 1.3634e-05,
         3.6227e-05, 5.0741e-01]])

In [31]:
tokens

tensor([[15496,    11,   314,  1101,   257,  3303,  2746,    11]])

In [32]:
input

"Hello, I'm a language model,"